### ISSUE TITLE
Implement Federated Averaging Algorithm

### ISSUE THREAD

**Issue by lunaticcoding** [lunaticcoding/PyTorchFederatedOptimizers#1]
# TODO's
- [x] Implement the federated averaging algorithm.
- [x] Test the algorithm.
- [x] Document usage of the algorithm in README.md

**Comment by lunaticcoding** [comment]
- [x] Add Integration Test for this algorithm
