### ISSUE TITLE
Implement Federated SVRG Algorithm

### ISSUE THREAD

**Issue by lunaticcoding** [lunaticcoding/PyTorchFederatedOptimizers#3]
# TODO's
- [ ] Write Tests.
- [ ] Implement the federated SVRG algorithm.
- [ ] Document usage of the algorithm in README.md
- [ ] Add integration test
