### ISSUE TITLE
Write automated Testing suite for all algorithms to test against

### ISSUE THREAD

**Issue by lunaticcoding** [lunaticcoding/PyTorchFederatedOptimizers#4]
# TODO's 
- [ ] Define metrics that show the algorithm to be working as intended.
- [ ] Implement these metrics in code
- [ ] Make testscript run for every commit with output as feedback
